/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardScansRouteImport } from './routes/dashboard/Scans'
import { Route as DashboardHomeRouteImport } from './routes/dashboard/home'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardScansRoute = DashboardScansRouteImport.update({
  id: '/dashboard/Scans',
  path: '/dashboard/Scans',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHomeRoute = DashboardHomeRouteImport.update({
  id: '/dashboard/home',
  path: '/dashboard/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/Scans': typeof DashboardScansRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/profile': typeof DashboardProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/Scans': typeof DashboardScansRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/profile': typeof DashboardProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard/Scans': typeof DashboardScansRoute
  '/dashboard/home': typeof DashboardHomeRoute
  '/dashboard/profile': typeof DashboardProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard/Scans'
    | '/dashboard/home'
    | '/dashboard/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/Scans'
    | '/dashboard/home'
    | '/dashboard/profile'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard/Scans'
    | '/dashboard/home'
    | '/dashboard/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardScansRoute: typeof DashboardScansRoute
  DashboardHomeRoute: typeof DashboardHomeRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/Scans': {
      id: '/dashboard/Scans'
      path: '/dashboard/Scans'
      fullPath: '/dashboard/Scans'
      preLoaderRoute: typeof DashboardScansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/home': {
      id: '/dashboard/home'
      path: '/dashboard/home'
      fullPath: '/dashboard/home'
      preLoaderRoute: typeof DashboardHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardScansRoute: DashboardScansRoute,
  DashboardHomeRoute: DashboardHomeRoute,
  DashboardProfileRoute: DashboardProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
